

services:
  app:
    image: 50995452/cicd_pipeline:latest
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    networks:
      - internal
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/examenTP
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgresSqlContainer
    ports:
      - "5432:5432"
    networks:
      - internal
    environment:
      POSTGRES_DB: examenTP
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadminContainer
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    depends_on:
      - db
    networks:
      - internal
      - external

  nginx:
    image: 50995452/cicd_pipeline_proxy:latest
    build:
      context: .
      dockerfile: DockerFileProxy
    container_name: customProxyContainer
    ports:
      - "80:80" # Expose port 80 to the host
    networks:
      - internal
    depends_on:
      - app

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
