name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest  # Fixed the incorrect syntax

    steps:
      - uses: actions/checkout@v3

      # Build the Spring Boot application
      - name: Build the Spring Boot application
        run: mvn clean install -DskipTests

      # Login to DockerHub (Improved Security)
      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Build and push the backend image
      - name: Build and Push Backend Image
        run: |
          docker build -f DockerFile -t 50995452/cicd_pipeline:latest .
          docker push 50995452/cicd_pipeline:latest

      # Build and push the proxy image
      - name: Build and Push Proxy Image
        run: |
          docker build -f DockerFileProxy -t 50995452/cicd_pipeline_proxy:latest .
          docker push 50995452/cicd_pipeline_proxy:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Fixed incorrect key
          script: |
            set -e  # Stop script on errors
            
            # Navigate to the deployment directory
            cd /home/${{ secrets.SSH_USER }}/TP---PPP || exit 1

            echo "Pulling the latest images..."
            docker-compose pull  # Use 'docker-compose' for compatibility

            echo "Restarting the services..."
            docker-compose down
            docker-compose up -d --remove-orphans

            echo "Cleaning up unused Docker images..."
            docker system prune -af  # More efficient cleanup
            #    needs: build
#    runs-on: [aws-ec2]
#
#
#    steps:
#      # Pull the latest images from DockerHub
#      - name: Pull latest images from Docker Hub
#        run: |
#          docker pull 50995452/cicd_pipeline:latest
#          docker pull 50995452/cicd_pipeline_proxy:latest
#
#      # Stop and remove existing containers
#      - name: Stop and Remove Old Containers
#        run: |
#          docker compose down || true
#          docker rm -f $(docker ps -aq --filter name=cicd_pipeline) || true
#          docker rm -f $(docker ps -aq --filter name=cicd_pipeline_proxy) || true
#
#      # Remove old images
#      - name: Remove old Docker images
#        run: |
#          docker rmi -f 50995452/cicd_pipeline:latest || true
#          docker rmi -f 50995452/cicd_pipeline_proxy:latest || true
#
#      # Start new containers using Docker Compose
#      - name: Start Containers using Docker Compose
#        run: |
#
#          cd /home/${{ secrets.SSH_USER }}/TP---PPP  # Adjust the path to your user directory
#          echo "Pulling the latest images..."
#          docker compose pull
#          echo "Restarting the services..."
#          docker compose down
#          docker compose up -d
#          echo "Cleaning up unused Docker images..."
#          docker image prune -af
#          docker compose up -d

          
           
